---
- name: grant "{{ ansible_user }}" passwordless sudo
  template:
    src: files/sudoers.d/100-user.j2
    dest: /etc/sudoers.d/100-user
    mode: "0600"
  when: ansible_facts.distribution != "FreeBSD"  # in opnsense: settings > administration > authentication > sudo
