---
- name: add proxmox gpg repo key
  apt_key:
    url: http://download.proxmox.com/debian/proxmox-release-bookworm.gpg
    state: present

- name: add proxmox backup client repository
  apt_repository:
    repo: deb http://download.proxmox.com/debian/pbs-client bookworm main
    state: present

- name: install proxmox backup client
  apt:
    pkg:
      - proxmox-backup-client
    state: latest
    update_cache: true
    autoclean: true

- name: _
  set_fact:
    proxmox_backup:
      backup_name: harriet-home.pxar
      backup_root: /home/harriet/
      include_timeshift: true
      timeshift_path: /timeshift/
      passwd_file: proxmox_backup_passwd
      username: backup_user@pbs
      token_name: "{{ ansible_hostname }}"
      server: backoops
      datastore: NVMe

- name: test backup password file
  stat:
    path: /root/.secrets/{{ proxmox_backup.passwd_file }}
  register: passwd_file

- name: assert that backup api token has been stored
  fail:
    msg: "Generate an API token for {{ proxmox_backup.username }} and store it at {{ proxmox_backup.passwd_file }}"
  ignore_errors: true
  when: not passwd_file.stat.exists or passwd_file.stat.size < 36

- name: create backup service directory
  file:
    path: /etc/proxmox-backup
    state: directory
    mode: 0755
  register: service_dir

- name: generate backup client config
  lineinfile:
    path: "{{ service_dir.path }}/proxmox-backup.env"
    regexp: ^{{ item.key }}=
    line: '{{ item.key }}="{{ item.value }}"'
    insertafter: EOF
    create: true
    mode: 0755
  loop: "{{ proxmox_backup | dict2items }}"

- name: copy backup service script
  copy:
    src: proxmox-backup.sh
    dest: "{{ service_dir.path }}"
    mode: 0755

- name: copy backup service configs
  template:
    src: files/proxmox-backup.{{ item }}.j2
    dest: /etc/systemd/system/proxmox-backup.{{ item }}
  loop:
    - timer
    - service

- name: disable backup service
  systemd:
    name: proxmox-backup.service
    enabled: false
    daemon_reload: false

- name: start backup timer
  systemd:
    name: proxmox-backup.timer
    enabled: true
    state: started
    daemon_reload: true
