---
- name: _
  set_fact:
    mail_passwd_file: /root/.secrets/mail_passwd
    placeholder_passwd: insert_app_password_here

- name: Check for mail password
  stat:
    path: "{{ mail_passwd_file }}"
  register: mail_passwd

- name: Pre-stage mail password
  when: not mail_passwd.stat.exists
  lineinfile:
    path: "{{ mail_passwd_file }}"
    line: "mail.runbox.com freddie.sackur@dustyfox.uk:insert_app_password_here"
    insertafter: EOF
    create: true
    mode: 0600

- name: Test for mail placeholder password
  shell: grep {{ placeholder_passwd }} {{ mail_passwd_file }}
  register: placeholder_test
  failed_when: false
  changed_when: false

- name: Fail when placeholder mail password is found  # don't want to lock out my account!
  when: placeholder_test.rc == 0
  fail:
    msg: "Update {{ mail_passwd_file }} with the app password for runbox"

- name: Create mail config directory
  file:
    path: /etc/mail/config
    state: directory

- name: Copy mail docker-compose
  template:
    src: mail.docker-compose.yml.j2
    dest: /etc/mail/docker-compose.yml

- name: Copy mail service conf
  template:
    src: mail.service
    dest: /etc/systemd/system/mail.service

- name: Copy mail postfix conf
  template:
    src: "postfix-main.cf"
    dest: /etc/mail/config/postfix-main.cf

# - include_tasks: container_user_profile.yml
#   vars:
#     profile_path: /etc/mail/root/

- name: Enable mail service
  service:
    name: mail
    enabled: true
    state: started
