---
- name: Generate pihole password file
  shell:
    cmd: tr -dc 'A-Za-z0-9@#$%&_+=' </dev/urandom 2>/dev/null | head -c32 > /root/.secrets/pihole_passwd
    creates: /root/.secrets/pihole_passwd

- name: Set pihole password file permissions
  file:
    path: /root/.secrets/pihole_passwd
    state: file
    mode: 0600

- name: Create pihole config directories
  file:
    path: /etc/pihole/{{ item }}
    state: directory
  loop:
    - dnsmasq.d
    - pihole
    - lighttpd/conf-enabled
    - root

- name: Copy pihole web config
  template:
    src: pihole.99-admin-redirect.conf
    dest: /etc/pihole/lighttpd/conf-enabled/99-admin-redirect.conf

- name: Copy pihole docker-compose
  template:
    src: pihole.docker-compose.yml.j2
    dest: /etc/pihole/docker-compose.yml

- name: Copy pihole service conf
  template:
    src: pihole.service
    dest: /etc/systemd/system/pihole.service

- include_tasks: container_user_profile.yml
  vars:
    profile_path: /etc/pihole/root/

- name: Enable pihole service
  service:
    name: pihole
    enabled: true
    state: started
