---
- name: Stevedore
  hosts: all
  become: true
  vars:
    network:
      dhcp4: false
      addresses:
        - 10.9.9.3/24
        - 10.9.9.9/24
      gateway4: 10.9.9.1
      nameservers:
        addresses:
          - 10.9.9.1
      search_suffix: leigh.delamere
    host_addresses:
      unifi: 10.9.9.9

  tasks:
    - include_tasks: network.yml

    - include_tasks: ../common/base.yml

    - name: Test docker binary
      stat:
        path: /usr/bin/docker
      register: docker

    - include_tasks: docker.yml
      when: not docker.stat.exists

    - name: Create .secrets directory
      file:
        path: /root/.secrets/
        state: directory
        mode: 0700
        owner: root
        group: root

    - include_tasks: unifi.yml
