---
- name: Stevedore
  hosts: all
  become: true
  vars:
    network:
      dhcp4: false
      addresses:
        - 10.9.9.3/24
        - 10.9.9.9/24
        - 10.9.9.53/24
      gateway4: 10.9.9.1
      cidr: 24
      nameservers:
        addresses:
          - 10.9.9.1
      search_suffix: leigh.delamere
    host_addresses:
      unifi: 10.9.9.9
      pihole: 10.9.9.53

  tasks:
    # - include_tasks: network.yml

    # - include_tasks: ../common/base.yml

    # - name: Test docker binary
    #   stat:
    #     path: /usr/bin/docker
    #   register: docker

    # - include_tasks: docker.yml
    #   when: not docker.stat.exists

    # - name: Create .secrets directory
    #   file:
    #     path: /root/.secrets/
    #     state: directory
    #     mode: 0700
    #     owner: root
    #     group: root

    # - include_tasks: pihole.yml

    # - include_tasks: unifi.yml

    # - name: set
    #   set_fact:
    #     # test: "{{ network.addresses | replace(network.cidr, '')  | replace('/', '') | to_yaml }}"
    #     # test: "{{ network.addresses | to_yaml }}"
    #     # test: "{{ network.addresses | ipaddr('address') }}"
    #     # test: "{{ network.addresses | ansible.utils.ipaddr('net') }}"
    #     test: "{{ network.addresses[0] | ipaddr(0) }}"



    # - name: d
    #   debug:
    #     var: test

    - name: Copy unifi docker-compose
      template:
        src: unifi.docker-compose.yml.j2
        dest: /etc/unifi/docker-compose.yml
