---
- import_tasks: updates.yml
  tags: updates

- import_tasks: user.yml

- import_tasks: tailscale.yml
  tags: tailscale

- import_tasks: wifi.yml
  tags: wifi

- import_tasks: cisco.yml
  tags: cisco
