---
- name: allow ip forwarding
  sysctl:
    sysctl_file: /etc/sysctl.d/22-ansible.conf
    name: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{
      {
        'net.ipv4.ip_forward': 1,
        'net.ipv6.conf.all.forwarding': 1
      } | dict2items
    }}"

- include_tasks:
    file: "{{ role_path }}/../tailscale/tasks/main.yml"
    apply:
      vars:
        tailscale_package: tailscale-pikvm
        tailscale_advertise_routes:
          - 10.9.9.0/24
          - 10.7.7.0/24
