---
- name: Docker host
  hosts: stevedore
  roles:
    - role: sshd
      tags: sshd
    - role: sudo
      tags: sudo
    - role: stevedore
      tags: os
    - role: docker
      tags: docker
    - role: unifi
      tags: unifi
    - role: postfix
      tags: postfix
  vars:
    network:
      dhcp4: false
      addresses:
        - 10.9.9.3/24
        - 10.9.9.9/24
        - 10.9.9.25/24
      gateway4: 10.9.9.1
      nameservers:
        addresses:
          - 10.9.9.1
      search_suffix: leigh.delamere
    host_addresses:
      unifi: 10.9.9.9
      mail: 10.9.9.25
  vars_files:
    - vars/vault_wrapper.yml
  become: true
