---
- name: install base packages
  package:
    name:
      - thunderbird
      - kitty
      - dirmngr
      - mc
      - fontconfig
      - gparted
      - wine
      - winetricks
      - wineglass
    state: latest
  tags: dnf

- name: install flatpaks
  flatpak:
    name:
      - us.zoom.Zoom
      - org.chromium.Chromium
      - org.kde.okular  # pdf view/edit
    method: system
  tags: flatpak
