---
- name: install dconf-editor
  package:
    name: dconf-editor
    state: present

- name: set dconf to use text file overlay over binary blob
  lineinfile:
    path: /etc/dconf/profile/user
    regexp: "^(service-db:keyfile/user|user-db:user)$"
    line: service-db:keyfile/user
    insertbefore: BOF
