---
- name: set renderer  # https://www.reddit.com/r/Fedora/comments/1h2tmjz/you_might_want_to_switch_gtks_renderer/
  lineinfile:
    path: /etc/environment
    line: GSK_RENDERER=ngl
    state: "{{ 'present' if ansible_facts.distribution_version == '41' else 'absent' }}"
  when: ansible_facts.distribution == "Fedora"

- name: install packaged extensions
  package:
    name:
      - gnome-extensions-app
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-user-theme
      - gnome-menus
      - gnome-tweaks
      - xdg-utils
      - gnome-monitor-config  # only works while there's an interactive session. Just set it manually.

- name: install extension manager
  flatpak:
    name: com.mattjakeman.ExtensionManager
    method: system

- name: declare required extensions
  set_fact:
    extensions:
      - name: PaperWM
        id: paperwm@paperwm.github.com
        user: freddie
      - name: Just Perfection
        id: just-perfection-desktop@just-perfection
        user: freddie
      - name: User Themes
        id: user-theme@gnome-shell-extensions.gcampax.github.com
        user: "{{ primary_user }}"
      - name: Dash to Panel
        id: dash-to-panel@jderose9.github.com
        user: "{{ primary_user }}"
      - name: ArcMenu
        id: arcmenu@arcmenu.com
        user: "{{ primary_user }}"
      - name: Hide Top Bar
        id: hidetopbar@mathieu.bidon.ca
        user: "{{ primary_user }}"
      - name: No overview at start-up
        id: no-overview@fthx
        user: "{{ primary_user }}"
  tags: gnome_shell_extensions

- name: ensure extension folder
  file:
    path: /usr/share/gnome-shell/extensions/
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: gnome_shell_extensions

- include_tasks:
    file: install_gnome_extension.yml
    apply:
      tags: gnome_shell_extensions
  loop: "{{ extensions }}"
  loop_control:
    loop_var: extension
  tags: gnome_shell_extensions

- name: enable extensions for {{ primary_user }}
  include_tasks: set_dconf.yml
  vars:
    user: "{{ primary_user }}"
    dconf_settings: |
      [org/gnome/shell]
      enabled-extensions=['launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com', 'arcmenu@arcmenu.com', 'no-overview@fthx']
  tags: gnome_shell_extensions

- name: configure extension settings for {{ primary_user }}
  include_tasks: set_dconf.yml
  vars:
    user: "{{ primary_user }}"
    file: files/dconf/look-and-feel.conf

- name: disable hot corners and dynamic workspaces
  include_tasks: set_dconf.yml
  vars:
    user: "{{ primary_user }}"
    file: files/dconf/activities-pane.conf

- name: copy wallpapers
  copy:
    src: files/backgrounds/linuxmint-vanessa/
    dest: /usr/share/backgrounds/linuxmint-vanessa/

- name: set wallpaper for freddie
  include_tasks: set_dconf.yml
  vars:
    user: freddie
    file: files/dconf/wallpaper.conf.j2
    wallpaper_path: /usr/share/backgrounds/linuxmint-vanessa/hlightbulb_greece.jpg

- name: set wallpaper for {{ primary_user }}
  include_tasks: set_dconf.yml
  vars:
    user: "{{ primary_user }}"
    file: files/dconf/wallpaper.conf.j2
    wallpaper_path: "{{ '/usr/share/backgrounds/linuxmint-vanessa/dhoefler_path.jpg' if primary_user == 'harriet' else '/usr/share/backgrounds/gnome/adwaita-l.jxl' }}"

- name: copy avatars
  copy:
    src: files/icons/{{ item.src }}
    dest: "{{ item.dest }}"
  loop:
    - src: coffee-512x512.png
      dest: /var/lib/AccountsService/icons/freddie
    - src: monkey-puzzle.png
      dest: /usr/share/pixmaps/faces/
    - src: monkey-puzzle-512x512.png
      dest: /var/lib/AccountsService/icons/harriet
    - src: mountain-512x512.png
      dest: /var/lib/AccountsService/icons/admin

- name: set avatar on login screen
  when: primary_user == 'freddie' or primary_user == 'harriet'
  template:
    src: files/icons/AccountsService.ini.j2
    dest: /var/lib/AccountsService/users/{{ primary_user }}
  vars:
    user: "{{ primary_user }}"

# Created with GDM Settings app
# https://github.com/orgs/gdm-settings/discussions/87
- name: set login background
  copy:
    src: files/themes/gnome-shell-theme.gresource
    dest: /usr/share/gnome-shell/gnome-shell-theme.gresource
    backup: true
