---
- lineinfile:
    path: /var/lib/AccountsService/users/{{ user_to_hide }}
    search_string: SystemAccount=
    line: SystemAccount=true
  register: system_account

- name: restart accounts daemon
  when: system_account.changed
  service:
    name: accounts-daemon
    state: restarted

- name: install xdotool
  package:
    name: xdotool

- name: copy switch-user command
  copy:
    src: files/switch-user
    dest: /usr/local/bin/
    mode: "0755"
