---
- import_tasks: dconf.yml
  tags: dconf

- import_tasks: user.yml
  tags: user

- import_tasks: fonts.yml
  tags: fonts

- import_tasks: apps.yml
  tags: apps

- import_tasks: firefox.yml
  tags: firefox

- import_tasks: gnome.yml
  tags: gnome

- import_tasks: hide_user.yml
  vars:
    user_to_hide: freddie
  tags: hide_user
