---
- name: install utils
  package:
    name:
      - clevis
      - seahorse
      - pam_script

- name: create nopasswdlogin group
  group:
    name: nopasswdlogin
    system: true

- name: grant passwordless login to nopasswdlogin group
  lineinfile:
    path: /etc/pam.d/gdm-password
    line: "auth        sufficient    pam_succeed_if.so user ingroup nopasswdlogin"
    insertbefore: BOF
    backup: true

- name: copy encryption tool
  copy:
    src: files/gnome-keyring-unlock/encrypt-passwd.sh
    dest: /usr/local/bin/encrypt-passwd
    owner: root
    group: root
    mode: "0755"

- name: create user for {{ primary_user }}
  user:
    name: "{{ primary_user }}"
    comment: "{{ primary_user }}"
    expires: -1
    createhome: true
    groups:
      - wheel
      - nopasswdlogin
    append: true
  register: create_account

- name: reset {{ primary_user }}'s password
  user:
    name: "{{ primary_user }}"
    password: "{{ user_account[primary_user].password | password_hash('sha512', 'idempotentsalt') }}"
  no_log: true
  when: (create_account.changed | default(False)) or (ansible_run_tags | select('eq', 'reset_password'))
  tags:
    - reset_password
    - never

- name: encrypt password for keyring unlocker
  shell:
    cmd: /usr/local/bin/encrypt-passwd "{{ passwd }}" > {{ user_passwd_file }}
  no_log: true
  become_user: "{{ primary_user }}"
  vars:
    passwd: "{{ user_account[primary_user].password }}"
    user_passwd_file: /home/{{ primary_user }}/.passwd-tpm
  when: (create_account.changed | default(False)) or (ansible_run_tags | select('eq', 'reset_password'))
  tags:
    - reset_password
    - never

- name: ensure dconf text overlay is present
  copy:
    content: ""
    force: false
    dest: /home/{{ user_ }}/.config/dconf/user.txt
    owner: "{{ user_ }}"
    group: "{{ user_ }}"
    mode: "0644"
  vars:
    user_: "{{ primary_user }}"

- name: enable automatic timed login for {{ primary_user }}
  shell:
    cmd: grep TimedLogin {{ gdm_conf_path }} || sed -i 's/\[daemon\]/[daemon]\n{{ '\n'.join(timed_login_settings) }}/g' {{ gdm_conf_path }}
  register: edit_gdm_custom_conf
  changed_when: not edit_gdm_custom_conf.stdout
  vars:
    gdm_conf_path: /etc/gdm/custom.conf
    timed_login_settings:
      - TimedLoginEnable=true
      - TimedLogin={{ primary_user }}
      - TimedLoginDelay=45

- name: disable screen lock for {{ primary_user }}
  include_tasks: set_dconf.yml
  vars:
    user: "{{ primary_user }}"
    dconf_settings: |
      [org/gnome/desktop/screensaver]
      lock-enabled=false

- name: grant {{ primary_user }} sudo to decrypt with tpm
  template:
    src: files/gnome-keyring-unlock/20-tss.j2
    dest: /etc/sudoers.d/20-tss
    owner: root
    group: root
    mode: "0600"
  vars:
    user: "{{ primary_user }}"

- name: install umglurf's gnome-keyring-unlock tool
  git:
    accept_newhostkey: true
    depth: 1
    dest: /usr/local/bin/gnome-keyring-unlock-umglurf
    repo: https://codeberg.org/umglurf/gnome-keyring-unlock

- name: copy gnome-keyring-unlock tool
  copy:
    src: files/gnome-keyring-unlock/gnome-keyring-unlock.sh
    dest: /usr/local/bin/gnome-keyring-unlock
    owner: root
    group: root
    mode: "0755"

- name: ensure user service folder
  file:
    path: /home/{{ primary_user }}/.config/systemd/user
    state: directory
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: "0755"

- name: copy gnome-keyring-unlock service
  template:
    src: files/gnome-keyring-unlock/gnome-keyring-unlock.service.j2
    dest: /home/{{ primary_user }}/.config/systemd/user/gnome-keyring-unlock.service
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: "0755"
  vars:
    user_passwd_file: /home/{{ primary_user }}/.passwd-tpm

- name: enable gnome-keyring-unlock service
  shell:
    cmd: |
      export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus" && \
      systemctl --user daemon-reload && \
      systemctl --user enable gnome-keyring-unlock
  register: enable_gnome_keyring_unlock
  changed_when: enable_gnome_keyring_unlock.stderr
  become_user: "{{ primary_user }}"

- include_tasks: ../../common/install_selinux_policy.yml
  loop:
    - passwd-write-home
    - passwd-sudo
    - passwd-sudo-map
    - passwd-tpm
  loop_control:
    loop_var: selinux_module

- name: copy pam script
  copy:
    src: files/gnome-keyring-unlock/tpm-passwd.sh
    dest: /etc/pam-script.d/tpm_passwd
    owner: root
    group: root
    mode: "0755"

- name: call password encryption in passwd pam module
  lineinfile:
    path: /etc/pam.d/passwd
    regexp: "password\\s+optional\\s+pam_script.so"
    line: "password   optional     pam_script.so    # invokes /etc/pam-script.d/*_passwd"
    insertbefore: "^\\s*-?password\\s+optional\\s+pam_gnome_keyring.so\\s+use_authtok"
    backup: true

- name: call password encryption only for nopasswdlogin group
  lineinfile:
    path: /etc/pam.d/passwd
    regexp: "password\\s.*\\spam_succeed_if.so \\w+ user ingroup nopasswdlogin"
    line: "password [default=1 success=ignore] pam_succeed_if.so quiet user ingroup nopasswdlogin"
    insertbefore: "password\\s+optional\\s+pam_script.so"
    backup: true
