---
- name: Create directory
  file:
    path: "{{ path | dirname }}"
    state: directory

- name: Generate {{ purpose }} password file
  shell:
    cmd: tr -dc '{{ charset }}' </dev/urandom 2>/dev/null | head -c {{ length }} > {{ path }}
    creates: "{{ path }}"

- name: Set {{ purpose }} password file permissions
  file:
    path: "{{ path }}"
    state: file
    mode: 0600
