---
- include_tasks: ../../common/install_selinux_policy.yml
  vars:
    selinux_module: gnome-remote-desktop

- name: install winpr-makecert
  package:
    name: freerdp

- set_fact:
    rdp_cert_folder: /var/lib/gnome-remote-desktop/.local/share/gnome-remote-desktop/certificates/

- name: ensure rdp folder
  file:
    path: "{{ rdp_cert_folder }}"
    state: directory
    owner: gnome-remote-desktop
    group: gnome-remote-desktop

- name: generate system rdp cert
  shell:
    cmd: sudo -u gnome-remote-desktop winpr-makecert -silent -rdp -n {{ ansible_hostname }}.leigh.delamere -path {{ rdp_cert_folder }} rdp-tls
    creates: "{{ rdp_cert_folder }}/rdp-tls.crt"

- name: configure system rdp
  shell:
    cmd: |
      grdctl --system rdp enable && \
      grdctl --system rdp disable-view-only && \
      grdctl --system rdp set-tls-key {{ rdp_cert_folder }}/rdp-tls.key && \
      grdctl --system rdp set-tls-cert {{ rdp_cert_folder }}/rdp-tls.crt

- name: set system rdp password
  shell:
    cmd: grdctl --system rdp set-credentials {{ primary_user }} "{{ vnc[ansible_hostname].password }}"
  no_log: true

- name: enable system rdp
  shell:
    cmd: systemctl daemon-reload && systemctl enable --now gnome-remote-desktop

- become_user: "{{ primary_user }}"
  vars:
    ansible_become_password: "{{ user_account[primary_user].password }}"
  block:
    - set_fact:
        rdp_cert_folder: /home/{{ primary_user }}/.local/share/gnome-remote-desktop/certificates/

    - name: ensure local certificate path
      file:
        path: "{{ rdp_cert_folder }}"
        state: directory
        owner: "{{ primary_user }}"
        group: "{{ primary_user }}"

    - name: generate user rdp cert
      shell:
        cmd: winpr-makecert -silent -rdp -n {{ ansible_hostname }}.leigh.delamere -path {{ rdp_cert_folder }} rdp-tls
        creates: "{{ rdp_cert_folder }}/rdp-tls.crt"

    - name: configure rdp desktop sharing
      shell:
        cmd: |
          export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus" && \
          grdctl rdp enable && \
          grdctl rdp disable-view-only && \
          grdctl rdp set-tls-key {{ rdp_cert_folder }}/rdp-tls.key && \
          grdctl rdp set-tls-cert {{ rdp_cert_folder }}/rdp-tls.crt

    - name: set rdp desktop sharing password
      shell:
        cmd: |
          export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus" && \
          grdctl rdp set-credentials {{ primary_user }} "{{ vnc[ansible_hostname].password }}"
      no_log: true

    - name: configure vnc desktop sharing
      shell:
        cmd: |
          export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus" && \
          grdctl vnc enable && \
          grdctl vnc disable-view-only && \
          grdctl vnc set-auth-method password && \
          grdctl vnc set-password "{{ vnc[ansible_hostname].password | truncate(8, True, '') }}"
      no_log: true

    - name: enable desktop sharing
      shell:
        cmd: |
          export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus" && \
          systemctl --user daemon-reload && \
          systemctl --user enable --now gnome-remote-desktop
