---
- name: name vlans
  notify: cisco_write_config
  cisco.ios.ios_config:
    lines:
      - description {{ item.value }}
    parents: interface Vlan{{ item.key }}
  loop: "{{ vlans | dict2items }}"
  tags: vlan

- name: set vlan ports
  notify: cisco_write_config
  cisco.ios.ios_config:
    lines:
      - switchport access vlan {{ item.value }}
    parents: interface GigabitEthernet0/{{ item.key }}
  loop: "{{ vlan_access_ports | dict2items }}"
  tags: vlan

- name: set vlan trunk ports
  notify: cisco_write_config
  cisco.ios.ios_config:
    lines:
      - switchport trunk encapsulation dot1q
      - switchport trunk native vlan {{ item.value }}
      - switchport mode trunk
    parents: interface GigabitEthernet0/{{ item.key }}
  loop: "{{ vlan_trunk_ports | dict2items }}"
  tags: vlan
