---
- set_fact:  # ensure trunk key is present
    ports: "{{
        ports |
        dict2items |
        map(attribute='value') |
        map(attribute='trunk', default=False) |
        map('community.general.dict_kv', 'trunk') |
        map('community.general.dict_kv', 'value') |
        zip(ports | dict2items) |
        map('combine', recursive=True) |
        items2dict
      }}"

- set_fact:  # ensure desc key is present
    ports: "{{
        ports |
        dict2items |
        map(attribute='value') |
        map(attribute='desc', default='unused') |
        map('community.general.dict_kv', 'desc') |
        map('community.general.dict_kv', 'value') |
        zip(ports | dict2items) |
        map('combine', recursive=True) |
        items2dict
      }}"

- set_fact:  # convert keys into port property
    ports: "{{
        ports.keys() |
        map('community.general.dict_kv', 'port') |
        map('community.general.dict_kv', 'value') |
        zip(ports | dict2items) |
        map('combine', recursive=True) |
        items2dict
      }}"

- set_fact:
    trunk_ports: "{{
        ports |
        dict2items |
        map(attribute='value') |
        selectattr('trunk')
      }}"
    access_ports: "{{
        ports |
        dict2items |
        map(attribute='value') |
        rejectattr('trunk')
      }}"

- name: set access ports
  notify: cisco_write_config
  cisco.ios.ios_config:
    lines:
      - description {{ item.desc }}
      - switchport access vlan {{ item.vlan }}
    parents: interface GigabitEthernet0/{{ item.port }}
  loop: "{{ access_ports }}"
  tags: vlan


- name: set vlan trunk ports
  notify: cisco_write_config
  cisco.ios.ios_config:
    lines:
      - description {{ item.desc }}
      - switchport trunk encapsulation dot1q
      - switchport trunk native vlan {{ item.vlan }}
      - switchport mode trunk
    parents: interface GigabitEthernet0/{{ item.port }}
  loop: "{{ trunk_ports }}"
  tags: vlan
