---
- name: install tailscale
  package:
    name: "{{ tailscale_package | default('tailscale') }}"

- name: add bash completions
  shell:
    cmd: tailscale completion bash > /etc/bash_completion.d/tailscale
    creates: /etc/bash_completion.d/tailscale

- name: enable tailscale service
  systemd:
    name: tailscaled
    daemon_reload: true
    enabled: true
    state: started

- name: check tailscale status
  shell:
    cmd: tailscale status
  failed_when: false
  changed_when: false
  register: tailscale_status

- set_fact:
    tailscale_status: >-
      {%- if tailscale_status.rc == 0 -%}
        up
      {%- elif 'Tailscale is stopped.' in tailscale_status.stdout_lines -%}
        down
      {%- elif 'Logged out.' in tailscale_status.stdout_lines -%}
        logged_out
      {%- else -%}
        {{ tailscale_status.stderr }}
      {%- endif -%}

- when: tailscale_status not in ['up', 'down', 'logged_out']
  fail:
    msg: "{{ tailscale_status }}"

- pause:
    prompt: Starting tailscale. This may drop the connection

- name: connect to tailscale
  when: tailscale_status == 'logged_out'
  shell:
    cmd: tailscale up --auth-key={{ tailscale_token }}?ephemeral=false --advertise-tags tag:{{ tailscale_tag }}
  vars:
    tailscale_token: "{{ tailscale.oauth[tailscale_tag].client_secret }}"
  no_log: true

- name: start tailscale
  when: tailscale_status == 'down'
  shell:
    cmd: tailscale up

- name: allow tailscale without sudo
  shell:
    cmd: tailscale set --operator {{ ansible_user }}

- name: accept tailscale routes
  shell:
    cmd: tailscale set --accept-routes --exit-node-allow-lan-access

- name: advertise tailscale routes
  when: tailscale_advertise_routes is defined
  shell:
    cmd: tailscale set --advertise-routes {{ tailscale_advertise_routes | join(',') }}

- name: accept tailscale ssh
  shell:
    cmd: tailscale set --ssh
