---
- set_fact:
    tailscale_package: "{{ tailscale_package | default('tailscale') }}"
    tailscale_advertise_routes: "{{ '--advertise-routes ' + routes if routes else '' }}"
  vars:
    routes: "{{ tailscale_advertise_routes | default([]) | join(',') }}"

- name: install tailscale
  package:
    name: "{{ tailscale_package }}"

- name: add bash completions
  shell:
    cmd: tailscale completion bash > /etc/bash_completion.d/tailscale
    creates: /etc/bash_completion.d/tailscale

- name: enable tailscale service
  systemd:
    name: tailscaled
    daemon_reload: true
    enabled: true
    state: started

- name: connect to tailscale
  shell:
    cmd: tailscale up --timeout 3s --accept-routes {{ tailscale_advertise_routes }} 2>&1
  register: tailscale_login
  timeout: 8
  failed_when: false

- when: tailscale_login.rc != 0
  block:
    - set_fact:
        waiting_auth: "{{
          tailscale_login.stdout_lines
          | select('match', '.*To authenticate, visit.*')
          | length > 0 }}"

    - when: waiting_auth
      pause:
        prompt: "Authenticate by visiting this URL in your browser: {{
          tailscale_login.stdout_lines
          | select('match', '.*https.*')
          | first
          | regex_replace('\\s+|$', '  ') }}"

    - when: not waiting_auth
      fail:
        msg: "{{ tailscale_login.stdout }}"
