---
- name: Check home folder encryption for {{ user }}
  stat:
    path: /home/.ecryptfs/{{ user }}
  register: ecryptfs

- name: Warn when home folder is not encrypted
  fail:
    msg: "/home/{{ user }} is not encrypted. Log on as root and run `ecryptfs-migrate-home -u {{ user }}`"
  ignore_errors: true
  when: not ecryptfs.stat.exists
