---
- name: Install x11vnc
  apt:
    pkg:
      - x11vnc
    state: latest
    update_cache: false   # presumably done recently
    autoclean: true

- name: _
  set_fact:
    vnc_passwd_path: /root/.secrets/vnc_passwd
    vnc_hashed_passwd_path: /root/.secrets/vnc_passwd_hash

- name: Test VNC password file
  stat:
    path: "{{ vnc_passwd_path }}"
  register: vnc_passwd

- name: Generate VNC password
  when: not vnc_passwd.stat.exists
  include_tasks: generate_password.yml
  vars:
    purpose: VNC
    path: "{{ vnc_passwd_path }}"
    charset: a-zA-Z0-9=!$^&*_+@#
    length: 32

- name: Generate VNC password hash
  when: not vnc_passwd.stat.exists
  shell:
    cmd: x11vnc -storepasswd $(cat {{ vnc_passwd_path }}) {{ vnc_hashed_passwd_path }}

- name: Copy x11vnc service conf
  template:
    src: x11vnc.service.j2
    dest: /etc/systemd/system/x11vnc.service

- name: Enable x11vnc service
  service:
    name: x11vnc
    enabled: true
    state: started
