---
- name: install dconf-editor
  package:
    name: dconf-editor
    state: present

- name: ensure dconf text overlay is present
  copy:
    content: ""
    force: false
    dest: /home/{{ item }}/.config/dconf/user.txt
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0644"
  loop:
    - freddie
    - harriet

- name: set dconf to use text file overlay over binary blob
  lineinfile:
    path: /etc/dconf/profile/user
    line: service-db:keyfile/user
    insertbefore: BOF
