---
- name: declare required fonts
  set_fact:
    font_dir: /usr/local/share/fonts
    fonts:
      - Hack
      - FiraCode
      - Meslo

- name: install fontconfig and mainline fonts
  package:
    name:
      - fontconfig
      - liberation-fonts-all
      - wine-fonts
    state: latest

- name: ensure fonts directory
  file:
    path: "{{ font_dir }}"
    state: directory

- include_tasks: install_font.yml
  loop: "{{ fonts }}"
  loop_control:
    loop_var: font
