---
- name: install packaged extensions
  package:
    name:
      - gnome-extensions-app
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-user-theme
      - gnome-tweak-tool
      - gnome-menus
      - xdg-utils

- name: install extension manager
  flatpak:
    name: com.mattjakeman.ExtensionManager
    method: system

- name: declare required extensions
  set_fact:
    extensions:
      - name: PaperWM
        id: paperwm@paperwm.github.com
        user: freddie
      - name: Just Perfection
        id: just-perfection-desktop@just-perfection
        user: freddie
      - name: User Themes
        id: user-theme@gnome-shell-extensions.gcampax.github.com
        user: harriet
      - name: Dash to Panel
        id: dash-to-panel@jderose9.github.com
        user: harriet
      - name: ArcMenu
        id: arcmenu@arcmenu.com
        user: harriet
      - name: Hide Top Bar
        id: hidetopbar@mathieu.bidon.ca
        user: harriet
  tags: gnome_shell_extensions

- name: ensure extension folder
  file:
    path: /usr/share/gnome-shell/extensions/
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags: gnome_shell_extensions

- include_tasks:
    file: install_gnome_extension.yml
    apply:
      tags: gnome_shell_extensions
  loop: "{{ extensions }}"
  loop_control:
    loop_var: extension
  tags: gnome_shell_extensions

- name: copy wallpapers
  copy:
    src: files/backgrounds/linuxmint-vanessa/
    dest: /usr/share/backgrounds/linuxmint-vanessa/
