---
- import_tasks: user.yml
  tags: user

- import_tasks: fonts.yml
  tags: fonts

- import_tasks: apps.yml
  tags: apps

# TODO: file picker

# TODO: backup / restore dconf settings
# wallpaper
# font scaling - inc bookwright
