---
- import_tasks: user.yml
  tags: user

- import_tasks: fonts.yml
  tags: fonts

- import_tasks: apps.yml
  tags: apps

- import_tasks: file_picker.yml
  tags: file_picker

- import_tasks: gnome.yml
  tags: gnome

- import_tasks: dconf.yml
  tags: dconf

# TODO:
# wallpaper
# font scaling - inc bookwright
