---
- name: install x11vnc
  package:
    name:
      - x11vnc

- name: _
  set_fact:
    vnc_passwd_path: /root/.secrets/vnc_passwd
    vnc_hashed_passwd_path: /root/.secrets/vnc_passwd_hash

- name: test vnc password file
  stat:
    path: "{{ vnc_passwd_path }}"
  register: vnc_passwd

- name: generate vnc password
  when: not vnc_passwd.stat.exists
  include_tasks: ../common/generate_password.yml
  vars:
    purpose: VNC
    path: "{{ vnc_passwd_path }}"
    charset: a-zA-Z0-9=!$^&*_+@#
    length: 32

- name: generate vnc password hash
  when: not vnc_passwd.stat.exists
  shell:
    cmd: x11vnc -storepasswd $(cat {{ vnc_passwd_path }}) {{ vnc_hashed_passwd_path }}

- name: copy x11vnc service conf
  template:
    src: files/x11vnc.service.j2
    dest: /etc/systemd/system/x11vnc.service

- name: enable x11vnc service
  service:
    name: x11vnc
    enabled: true
    state: started
