---
- name: harriet-desktop
  hosts: all
  become: true
  tasks:
    - include_tasks: ../common/base.yml

    - include_tasks: ../common/vnc_server.yml

    - include_tasks: ../common/fonts.yml

    - name: Assert that Freddie's home folder is encrypted  # Must be done interactively
      include_tasks: ../common/check_home_folder_encryption.yml
      vars:
        user: freddie

    - name: Add VS Code repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Install base packages
      apt:
        pkg:
          - nohang
          - kitty
          - dirmngr
          - code
          - fontconfig
          - gparted
        state: latest
        update_cache: true
        autoclean: true

    - name: Enable nohang-desktop service
      service:
        name: nohang-desktop
        enabled: true
        state: started

    - name: Copy kitty config
      copy:
        src: kitty
        dest: "{{ ansible_user_home }}/.config/"
        force: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: false

    - name: Install flatpaks
      flatpak:
        name: "{{ item }}"
        method: system
      loop:
        - Zoom

    - name: Get timeshift partition UUID
      shell: lsblk -o NAME,LABEL,UUID | grep timeshift | awk '{print $NF}'
      register: _timeshift_partition_uuid
      changed_when: false
      failed_when:
        _timeshift_partition_uuid.rc != 0 or
        _timeshift_partition_uuid.stdout == "" or
        _timeshift_partition_uuid.stdout_lines|length != 1

    - name: _
      set_fact:
        timeshift_partition_uuid: "{{ _timeshift_partition_uuid.stdout }}"

    - name: Copy timeshift config
      template:
        src: timeshift.json.j2
        dest: /etc/timeshift/timeshift.json
        owner: root
        group: root
        mode: 0644
