---
- name: harriet-desktop
  hosts: all
  become: true
  tasks:
    - include_tasks: ../common/base.yml

    - include_tasks: ../common/vnc_server.yml

    - include_tasks: ../common/fonts.yml

    - name: Add VS Code repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Install base packages
      apt:
        pkg:
          - nohang
          - kitty
          - dirmngr
          - code
          - fontconfig
        state: latest
        update_cache: true
        autoclean: true

    - name: Enable nohang-desktop service
      service:
        name: nohang-desktop
        enabled: true
        state: started
