---
- name: harriet-desktop
  hosts: all
  become: true
  tasks:
    - include_tasks: ../common/base.yml

    - include_tasks: ../common/vnc_server.yml

    - include_tasks: ../common/fonts.yml

    - name: Assert that Freddie's home folder is encrypted  # Must be done interactively
      include_tasks: ../common/check_home_folder_encryption.yml
      vars:
        user: freddie

    - name: Add VS Code repository
      apt_repository:
        repo: deb https://packages.microsoft.com/repos/vscode stable main
        state: present

    - name: Install base packages
      apt:
        pkg:
          - nohang
          - kitty
          - dirmngr
          - code
          - fontconfig
        state: latest
        update_cache: true
        autoclean: true

    - name: Enable nohang-desktop service
      service:
        name: nohang-desktop
        enabled: true
        state: started

    - name: Copy kitty config
      copy:
        src: kitty.conf
        dest: "{{ ansible_user_home }}/.config/kitty/kitty.conf"
        force: false
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Install flatpaks
      flatpak:
        name: "{{ item }}"
        method: system
      loop:
        - Zoom
