---
- name: install timeshift
  package:
    name: timeshift

- name: get timeshift partition uuid
  shell:
    cmd: lsblk -o NAME,LABEL,UUID | grep timeshift | awk '{print $NF}'
  register: _timeshift_partition_uuid
  changed_when: false
  failed_when:
    _timeshift_partition_uuid.rc != 0 or
    _timeshift_partition_uuid.stdout == "" or
    _timeshift_partition_uuid.stdout_lines | length != 1

- name: _
  set_fact:
    timeshift_partition_uuid: "{{ _timeshift_partition_uuid.stdout }}"

- name: copy timeshift config
  template:
    src: files/timeshift.json.j2
    dest: /etc/timeshift/timeshift.json
    owner: root
    group: root
    mode: 0644

- name: create timeshift mount point
  file:
    path: /timeshift
    state: directory
    mode: 0644

- name: mount timeshift partition
  lineinfile:
    path: /etc/fstab
    regexp: ^UUID={{ timeshift_partition_uuid }}
    line: "UUID={{ timeshift_partition_uuid }} /timeshift              ext4    nofail          0       99"
    insertafter: EOF
    state: present
