---
- name: grant admins passwordless sudo
  copy:
    src: files/usr/local/etc/sudoers.d/opnsense
    dest: /usr/local/etc/sudoers.d/opnsense
    mode: "0640"
    owner: root
    group: wheel

- name: disable bracketed paste
  copy:
    src: files/etc/inputrc
    dest: /etc/inputrc
    mode: "0755"
    owner: root
    group: wheel

- name: install base packages
  package:
    name:
      - bash  # chsh has no effect; to change shell, System > Access > Users > Edit
      - nano
      - bind-tools

- name: copy sideload helper
  copy:
    src: files/sideload.sh
    dest: /usr/local/bin/sideload.sh
    mode: "0755"
    owner: root
    group: wheel

- name: check for pip
  shell:
    cmd: which pip
  register: pip_exists
  changed_when: false
  failed_when: false

- name: get pip sideload invocation
  shell:
    cmd: sideload.sh py311-pip
  register: sideload_command
  when: pip_exists.rc != 0
  changed_when: false
  failed_when: sideload_command.rc != 0 or sideload_command.stdout_lines | length != 1

- name: sideload pip
  shell:
    cmd: "{{ sideload_command.stdout }}"
  when: pip_exists.rc != 0

- set_fact:
    opnsense_packages:
      - os-qemu-guest-agent
      - os-bind
      - os-iperf
      - os-git-backup
      - os-ddclient
      - os-theme-advanced
      - os-theme-vicuna
      - os-theme-rebellion
      - os-theme-cicada

- name: check installed opnsense packages
  delegate_to: localhost
  become: false
  shell:
    cmd: opn-cli -c ~/.opn-cli/conf.{{ ansible_hostname }}.yaml plugin installed
  register: installed_opnsense_packages
  changed_when: false

- name: install opnsense packages
  delegate_to: localhost
  become: false
  shell:
    cmd: opn-cli -c ~/.opn-cli/conf.{{ ansible_hostname }}.yaml plugin install {{ item }}
  when: not installed_opnsense_packages.stdout_lines | select('match', ('.*\\b' + item + '\\b.*'))
  loop: "{{ opnsense_packages }}"
