---
- name: decrypt config
  delegate_to: localhost
  become: false
  shell:
    cmd: ansible-vault view '{{ opnsense_backup_path }}'
  register: decryption_result
  ignore_errors: true

- name: restore config
  copy:
    dest: /conf/config.xml
    content: "{{ decryption_result.stdout }}"
    mode: "0640"
    owner: root
    group: wheel
  register: restore_result

- name: reboot
  reboot:
     reboot_timeout: 120
  when: restore_result.changed
