---
- name: Harriet's desktop and laptop
  hosts:
    - harriet-desktop
    - harriet-laptop
  roles:
    - role: base
      tags: base
    - role: vnc_server
      tags: vnc_server
    - role: proxmox_backup
      tags: proxmox_backup
    - role: desktop
      tags: desktop
  become: true
