---
- name: Docker host
  hosts: stevedore
  roles:
    - role: sshd
      tags: sshd
    - role: sudo
      tags: sudo
    - role: docker
      tags: docker
    - role: unifi
      tags: unifi
  become: true
